version: '3.9'

services:
  app:
    restart: on-failure
    build:
      context: ..
      dockerfile: Dockerfile.app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/HandMadeStore
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: qweasd


  db:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: HandMadeStore
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qweasd
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
